production:
  <<: *default
  host: localhost
  adapter: mysql2
  encoding: utf8
  database: aggretools_prod
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  username: <%= ENV['APPNAME_DATABASE_USER'] %>
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>
